package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Nat;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.estimator.SwerveDrivePoseEstimator;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.kinematics.SwerveDriveOdometry;
import edu.wpi.first.math.kinematics.SwerveModulePosition;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

import frc.robot.generated.LimelightHelpers;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;

import edu.wpi.first.networktables.StructPublisher;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class SS_Drivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    public final Pigeon2 pidgey = new Pigeon2(50, "SwerveBus");

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    // public SwerveDriveKinematics swerveKinematics = new
    // SwerveDriveKinematics(getModuleLocations());
    // public SwerveDrivePoseEstimator poseEstimator = new
    // SwerveDrivePoseEstimator(swerveKinematics, kBlueAlliancePerspectiveRotation,
    // null, null);

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    public SwerveDriveKinematics kinematics = new SwerveDriveKinematics(new Translation2d[] {
        new Translation2d(Inches.of(10), Inches.of(10)),
        new Translation2d(Inches.of(10), Inches.of(-10)),
        new Translation2d(Inches.of(-10), Inches.of(10)),
        new Translation2d(Inches.of(-10), Inches.of(-10))
    });
    
    public SwerveModulePosition[] modulePositions = new SwerveModulePosition[] {
        getModule(0).getPosition(true),
        getModule(1).getPosition(true),
        getModule(2).getPosition(true),
        getModule(3).getPosition(true)
    };

    public SwerveDriveOdometry poseOdometry = new SwerveDriveOdometry(
        kinematics, 
        kBlueAlliancePerspectiveRotation, 
        modulePositions,
        new Pose2d(1.40, 4.84, new Rotation2d(0))
    );

    public SwerveDrivePoseEstimator poseEstimator = new SwerveDrivePoseEstimator(
        kinematics, 
        kBlueAlliancePerspectiveRotation, 
        modulePositions, 
        new Pose2d(1.40, 4.84, new Rotation2d(0)), 
        new Matrix<N3, N1>(Nat.N3(), Nat.N1(), new double[] {0.2, 0.2, 0.2}), 
        new Matrix<N3, N1>(Nat.N3(), Nat.N1(), new double[] {0.6, 0.6, 0.5})
    );

    Pose2d robotSimPose;
    Pose2d robotOdoPose;
    Pose2d robotLLPose;
    NetworkTable poseTable = NetworkTableInstance.getDefault().getTable("estimations");
    StructPublisher<Pose2d> posePublisher = poseTable.getStructTopic("poseEstimate", Pose2d.struct).publish();
    Field2d estimatedField = new Field2d();
    Field2d limelightField = new Field2d();
    Field2d odometryField = new Field2d();
    double[] limelightEstimate = new double[6];
    double stdDev;
    Rotation2d gyroAngle;
    double gyroSpeed;
    int loopCount = 0;
    SwerveModule module0 = getModule(0);
    SwerveModule module1 = getModule(1);
    SwerveModule module2 = getModule(2);
    SwerveModule module3 = getModule(3);

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    NetworkTable limelightTable = NetworkTableInstance.getDefault().getTable("limelight");
    double[] poseEstimate;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */

    public Translation2d[] moduleLocations;

    public SS_Drivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        poseEstimate = limelightTable.getEntry("botpose_orb_wpiblue").getDoubleArray(new double[6]);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public SS_Drivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public SS_Drivetrain(SwerveDrivetrainConstants drivetrainConstants, double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation, Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Command pigeonCommand() {
        return run(() -> this.pidgey.setYaw(0));
    }

    public void updateOdometry() {
        //Increment the loop count
        loopCount++;

        if (loopCount == 4) {
            loopCount = 0;

            //Get the Pigeon orientation and speed
            gyroAngle = pidgey.getRotation2d();
            gyroSpeed = pidgey.getAngularVelocityZDevice().getValueAsDouble();

            //Update and access the vision estimation
            LimelightHelpers.SetRobotOrientation("limelight", gyroAngle.getDegrees(), gyroSpeed, 0, 0, 0, 0);
            LimelightHelpers.PoseEstimate megaTag2 = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight");

            //Update with odometry first
            modulePositions[0] = module0.getPosition(true);
            modulePositions[1] = module1.getPosition(true);
            modulePositions[2] = module2.getPosition(true);
            modulePositions[3] = module3.getPosition(true);
            
            //Updating a pure odometry as well to compare for testing
            poseEstimator.update(gyroAngle, modulePositions);
            poseOdometry.update(gyroAngle, modulePositions);

            //Update vision stuff if we can
            //Don't update if the angular velocity is too high or we don't see any tags.
            if((Math.abs(pidgey.getAngularVelocityZDevice().getValueAsDouble()) < 720) && (megaTag2.tagCount != 0))
            {
                stdDev = MathUtil.clamp(1.05*megaTag2.avgTagDist/megaTag2.tagCount, 0.15, 1.1);
                Pose2d poseCorrection = new Pose2d(megaTag2.pose.getTranslation(), gyroAngle); //Ignore the rotation part of vision
                poseEstimator.setVisionMeasurementStdDevs(VecBuilder.fill(stdDev, stdDev, 0.5));
                poseEstimator.addVisionMeasurement(
                poseCorrection,
                megaTag2.timestampSeconds);
            }

            // System.out.println("FL dist " + modulePositions[0].distanceMeters);
            // System.out.println("angle " + modulePositions[0].angle.getDegrees());
            // System.out.println("pigeon " + pidgey.getYaw().getValueAsDouble());
            // System.out.println("module position " + getModule(0).getPosition(true).angle.getDegrees());
            // System.out.println("poseEstimate " + poseEstimator.getEstimatedPosition().toString());

            //Access the poses for each method
            robotSimPose = poseEstimator.getEstimatedPosition();

            limelightEstimate = limelightTable.getEntry("botpose_orb_wpiblue").getDoubleArray(limelightEstimate);
            
            robotLLPose = new Pose2d(limelightEstimate[0], limelightEstimate[1], new Rotation2d(Math.PI*limelightEstimate[5]/180));

            robotOdoPose = poseOdometry.getPoseMeters();

            // poseTable.getEntry("robotPose").setValue(robotSimPose);
            // posePublisher.set(robotSimPose);

            //Put the poses on the fields
            estimatedField.setRobotPose(robotSimPose);
            limelightField.setRobotPose(robotLLPose);
            odometryField.setRobotPose(robotOdoPose);

            //Add the fields
            SmartDashboard.putData("estimationField", estimatedField);
            SmartDashboard.putData("limelightField", limelightField);
            SmartDashboard.putData("odometryField", odometryField);
            
            //Other variables
            // SmartDashboard.putNumber("limelightDistance", limelightTable.getEntry("botpose_orb_wpiblue").getDoubleArray(new double[11])[9]);
            // SmartDashboard.putNumberArray("limelightPose", limelightEstimate);
            // SmartDashboard.putString("odometry", robotOdoPose.toString());
        }
    }
}
